version: '3.8'

services:
  product-write-api:
    container_name: product-write-api
    image: productwrite
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoSettings__ConnectionString=mongodb://mongo:27017
      - MongoSettings__DatabaseName=ProductDb
    depends_on:
      - mongo
    networks:
      - default

  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: [ "--replSet", "rs0" ]
    volumes:
      - mongo-data:/data/db
    networks:
      - default

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    networks:
      - default

volumes:
  mongo-data:

networks:
  default:
    name: debezium-net
    external: true
